// <auto-generated />
using System;
using AirlineReservation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirlineReservation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260909155108_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirlineReservation.Models.Airport", b =>
                {
                    b.Property<int>("AirportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AirportId"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("AirportId");

                    b.HasIndex("CityId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("AirlineReservation.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("BlockingNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookingStatus")
                        .HasColumnType("int");

                    b.Property<int>("BookingType")
                        .HasColumnType("int");

                    b.Property<string>("CancellationNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ConfirmationNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int?>("ItineraryId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfAdults")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfChildren")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSeniors")
                        .HasColumnType("int");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("BlockingNumber")
                        .IsUnique()
                        .HasFilter("[BlockingNumber] IS NOT NULL");

                    b.HasIndex("ConfirmationNumber")
                        .IsUnique()
                        .HasFilter("[ConfirmationNumber] IS NOT NULL");

                    b.HasIndex("FlightId");

                    b.HasIndex("ItineraryId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("AirlineReservation.Models.CancellationRule", b =>
                {
                    b.Property<int>("CancellationRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CancellationRuleId"));

                    b.Property<int?>("MaximumDaysBeforeDeparture")
                        .HasColumnType("int");

                    b.Property<int>("MinimumDaysBeforeDeparture")
                        .HasColumnType("int");

                    b.Property<decimal>("RefundPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("CancellationRuleId");

                    b.ToTable("CancellationRules");

                    b.HasData(
                        new
                        {
                            CancellationRuleId = 1,
                            MinimumDaysBeforeDeparture = 14,
                            RefundPercentage = 100m
                        },
                        new
                        {
                            CancellationRuleId = 2,
                            MaximumDaysBeforeDeparture = 13,
                            MinimumDaysBeforeDeparture = 7,
                            RefundPercentage = 75m
                        },
                        new
                        {
                            CancellationRuleId = 3,
                            MaximumDaysBeforeDeparture = 6,
                            MinimumDaysBeforeDeparture = 0,
                            RefundPercentage = 25m
                        });
                });

            modelBuilder.Entity("AirlineReservation.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("DistanceToNearestServicedCity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("NearestServicedCityId")
                        .HasColumnType("int");

                    b.Property<string>("StateOrRegion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CityId");

                    b.HasIndex("CityName")
                        .IsUnique();

                    b.HasIndex("NearestServicedCityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "New York"
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "Los Angeles"
                        },
                        new
                        {
                            CityId = 3,
                            CityName = "Chicago"
                        },
                        new
                        {
                            CityId = 4,
                            CityName = "Miami"
                        });
                });

            modelBuilder.Entity("AirlineReservation.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightId"));

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("time");

                    b.Property<int>("BusinessSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("time");

                    b.Property<int?>("DestinationAirportId")
                        .HasColumnType("int");

                    b.Property<int>("DestinationCityId")
                        .HasColumnType("int");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("EconomySeats")
                        .HasColumnType("int");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("FlightStatus")
                        .HasColumnType("int");

                    b.Property<int?>("OriginAirportId")
                        .HasColumnType("int");

                    b.Property<int>("OriginCityId")
                        .HasColumnType("int");

                    b.Property<decimal>("TicketPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FlightId");

                    b.HasIndex("DestinationAirportId");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("FlightNumber")
                        .IsUnique();

                    b.HasIndex("OriginAirportId");

                    b.HasIndex("OriginCityId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            ArrivalTime = new TimeSpan(0, 11, 15, 0, 0),
                            BusinessSeats = 20,
                            DepartureDate = new DateTime(2030, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 8, 0, 0, 0),
                            DestinationCityId = 2,
                            Duration = "6h 15m",
                            EconomySeats = 120,
                            FlightNumber = "AR101",
                            FlightStatus = 0,
                            OriginCityId = 1,
                            TicketPrice = 329.99m
                        },
                        new
                        {
                            FlightId = 2,
                            ArrivalTime = new TimeSpan(0, 17, 0, 0, 0),
                            BusinessSeats = 16,
                            DepartureDate = new DateTime(2030, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 9, 30, 0, 0),
                            DestinationCityId = 4,
                            Duration = "4h 30m",
                            EconomySeats = 150,
                            FlightNumber = "AR202",
                            FlightStatus = 0,
                            OriginCityId = 2,
                            TicketPrice = 279.99m
                        });
                });

            modelBuilder.Entity("AirlineReservation.Models.FlightFare", b =>
                {
                    b.Property<int>("FlightFareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightFareId"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FlightScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("SeatClassId")
                        .HasColumnType("int");

                    b.HasKey("FlightFareId");

                    b.HasIndex("FlightScheduleId");

                    b.HasIndex("SeatClassId");

                    b.ToTable("FlightFares");
                });

            modelBuilder.Entity("AirlineReservation.Models.FlightSchedule", b =>
                {
                    b.Property<int>("FlightScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightScheduleId"));

                    b.Property<int>("AvailableBusinessSeats")
                        .HasColumnType("int");

                    b.Property<int>("AvailableEconomySeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("FlightScheduleId");

                    b.HasIndex("FlightId");

                    b.ToTable("FlightSchedules");
                });

            modelBuilder.Entity("AirlineReservation.Models.Itinerary", b =>
                {
                    b.Property<int>("ItineraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItineraryId"));

                    b.Property<int>("Adults")
                        .HasColumnType("int");

                    b.Property<int>("Children")
                        .HasColumnType("int");

                    b.Property<string>("OnwardLegIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReturnLegIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatClassId")
                        .HasColumnType("int");

                    b.Property<int>("Seniors")
                        .HasColumnType("int");

                    b.Property<int>("TripType")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ItineraryId");

                    b.HasIndex("UserId");

                    b.ToTable("Itineraries");
                });

            modelBuilder.Entity("AirlineReservation.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledSendDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Sent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("BookingId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AirlineReservation.Models.Passenger", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassengerId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PassengerType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PassengerId");

                    b.HasIndex("BookingId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("AirlineReservation.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("CreditCardNumberMasked")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("BookingId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("AirlineReservation.Models.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<int>("DestinationCityId")
                        .HasColumnType("int");

                    b.Property<string>("FlightIds")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IntermediateStops")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OriginCityId")
                        .HasColumnType("int");

                    b.Property<string>("TotalDuration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RouteId");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("OriginCityId", "DestinationCityId")
                        .IsUnique();

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("AirlineReservation.Models.SeatClass", b =>
                {
                    b.Property<int>("SeatClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatClassId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("SeatClassId");

                    b.ToTable("SeatClasses");
                });

            modelBuilder.Entity("AirlineReservation.Models.SkyMilesTransaction", b =>
                {
                    b.Property<int>("SkyMilesTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkyMilesTransactionId"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MilesChange")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SkyMilesTransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("SkyMilesTransactions");
                });

            modelBuilder.Entity("AirlineReservation.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LoginId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PreferredCreditCard")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("SkyMiles")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "demo@example.com",
                            FirstName = "Demo",
                            LastName = "Traveler",
                            Password = "ChangeMe123!",
                            Role = 2,
                            SkyMiles = 2500,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AirlineReservation.Models.Airport", b =>
                {
                    b.HasOne("AirlineReservation.Models.City", "City")
                        .WithMany("Airports")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("AirlineReservation.Models.Booking", b =>
                {
                    b.HasOne("AirlineReservation.Models.Flight", "Flight")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirlineReservation.Models.Itinerary", "Itinerary")
                        .WithMany("Bookings")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AirlineReservation.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Itinerary");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirlineReservation.Models.City", b =>
                {
                    b.HasOne("AirlineReservation.Models.City", "NearestServicedCity")
                        .WithMany("NearbyCities")
                        .HasForeignKey("NearestServicedCityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NearestServicedCity");
                });

            modelBuilder.Entity("AirlineReservation.Models.Flight", b =>
                {
                    b.HasOne("AirlineReservation.Models.Airport", "DestinationAirport")
                        .WithMany("DestinationFlights")
                        .HasForeignKey("DestinationAirportId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AirlineReservation.Models.City", "DestinationCity")
                        .WithMany("DestinationFlights")
                        .HasForeignKey("DestinationCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirlineReservation.Models.Airport", "OriginAirport")
                        .WithMany("OriginFlights")
                        .HasForeignKey("OriginAirportId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AirlineReservation.Models.City", "OriginCity")
                        .WithMany("OriginFlights")
                        .HasForeignKey("OriginCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationAirport");

                    b.Navigation("DestinationCity");

                    b.Navigation("OriginAirport");

                    b.Navigation("OriginCity");
                });

            modelBuilder.Entity("AirlineReservation.Models.FlightFare", b =>
                {
                    b.HasOne("AirlineReservation.Models.FlightSchedule", "FlightSchedule")
                        .WithMany("Fares")
                        .HasForeignKey("FlightScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirlineReservation.Models.SeatClass", "SeatClass")
                        .WithMany("Fares")
                        .HasForeignKey("SeatClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FlightSchedule");

                    b.Navigation("SeatClass");
                });

            modelBuilder.Entity("AirlineReservation.Models.FlightSchedule", b =>
                {
                    b.HasOne("AirlineReservation.Models.Flight", "Flight")
                        .WithMany("Schedules")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("AirlineReservation.Models.Itinerary", b =>
                {
                    b.HasOne("AirlineReservation.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirlineReservation.Models.Notification", b =>
                {
                    b.HasOne("AirlineReservation.Models.Booking", "Booking")
                        .WithMany("Notifications")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirlineReservation.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirlineReservation.Models.Passenger", b =>
                {
                    b.HasOne("AirlineReservation.Models.Booking", "Booking")
                        .WithMany("Passengers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("AirlineReservation.Models.Payment", b =>
                {
                    b.HasOne("AirlineReservation.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("AirlineReservation.Models.Route", b =>
                {
                    b.HasOne("AirlineReservation.Models.City", null)
                        .WithMany()
                        .HasForeignKey("DestinationCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirlineReservation.Models.City", null)
                        .WithMany()
                        .HasForeignKey("OriginCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AirlineReservation.Models.SkyMilesTransaction", b =>
                {
                    b.HasOne("AirlineReservation.Models.User", "User")
                        .WithMany("SkyMilesTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirlineReservation.Models.Airport", b =>
                {
                    b.Navigation("DestinationFlights");

                    b.Navigation("OriginFlights");
                });

            modelBuilder.Entity("AirlineReservation.Models.Booking", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Passengers");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("AirlineReservation.Models.City", b =>
                {
                    b.Navigation("Airports");

                    b.Navigation("DestinationFlights");

                    b.Navigation("NearbyCities");

                    b.Navigation("OriginFlights");
                });

            modelBuilder.Entity("AirlineReservation.Models.Flight", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("AirlineReservation.Models.FlightSchedule", b =>
                {
                    b.Navigation("Fares");
                });

            modelBuilder.Entity("AirlineReservation.Models.Itinerary", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("AirlineReservation.Models.SeatClass", b =>
                {
                    b.Navigation("Fares");
                });

            modelBuilder.Entity("AirlineReservation.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Notifications");

                    b.Navigation("SkyMilesTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
